networkerstech/sertresdelnorte

s_insure_fleet/__init__.py
s_insure_fleet/__manifest__.py
s_insure_fleet/data/s_insure_fleet_data.xml
s_insure_fleet/i18n/es_MX.po
s_insure_fleet/models/__init__.py
s_insure_fleet/models/inherit_fleet_vehicle.py
s_insure_fleet/security/ir.model.access.csv
s_insure_fleet/views/inherit_fleet_vehicle_views.xml

MOD: s_insure_fleet
Desarrollo: 3
Punto: 1

TEST: Add insure fleet

---

s_services_fleet/__init__.py
s_services_fleet/__manifest__.py
s_services_fleet/data/s_services_fleet_data.xml
s_services_fleet/models/__init__.py
s_services_fleet/models/inherit_fleet_vehicle.py
s_services_fleet/security/ir.model.access.csv
s_services_fleet/views/templates.xml
s_services_fleet/views/views.xml

MOD: s_services_fleet
Desarrollo: 3
Punto: 2

TEST: ADD service fleet

---

s_criteria_expiration/__init__.py
s_criteria_expiration/__manifest__.py
s_criteria_expiration/data/criteria_expiration_menu.xml
s_criteria_expiration/i18n/es_MX.po
s_criteria_expiration/models/__init__.py
s_criteria_expiration/models/cargo_permit.py
s_criteria_expiration/models/insurance_policy.py
s_criteria_expiration/models/vehicle_service.py
s_criteria_expiration/security/ir.model.access.csv
s_criteria_expiration/views/cargo_permit_views.xml
s_criteria_expiration/views/insurance_policy_views.xml
s_criteria_expiration/views/vehicle_service_views.xml

MOD: s_criteria_expiration
Desarrollo: 3
Punto: 3

ADD criteria expiration

---

s_car_expensive/__init__.py
s_car_expensive/__manifest__.py
s_car_expensive/models/__init__.py
s_car_expensive/models/inherit_hr_expenses.py
s_car_expensive/security/ir.model.access.csv
s_car_expensive/views/inherit_hr_expense_view.xml

MOD: s_car_expensive
Desarrollo 2
Punto 1

TEST: ADD Car expensive

---

s_car_expensive/__init__.py
s_car_expensive/__manifest__.py
s_car_expensive/models/__init__.py
s_car_expensive/models/inherit_hr_expenses.py
s_car_expensive/security/ir.model.access.csv
s_car_expensive/views/inherit_hr_expense_view.xml

MOD - s_car_expensive
Desarrollo 2 , Punto 1

ADD Car expensive

---

s_insure_fleet/__init__.py
s_insure_fleet/__manifest__.py
s_insure_fleet/data/s_insure_fleet_data.xml
s_insure_fleet/i18n/es_MX.po
s_insure_fleet/models/__init__.py
s_insure_fleet/models/inherit_fleet_vehicle.py
s_insure_fleet/security/ir.model.access.csv
s_insure_fleet/views/inherit_fleet_vehicle_views.xml

MOD: s_insure_fleet
Desarrollo: 3
Punto: 1

Add insure fleet

---

s_services_fleet/__init__.py
s_services_fleet/__manifest__.py
s_services_fleet/data/s_services_fleet_data.xml
s_services_fleet/models/__init__.py
s_services_fleet/models/inherit_fleet_vehicle.py
s_services_fleet/security/ir.model.access.csv
s_services_fleet/views/templates.xml
s_services_fleet/views/views.xml

MOD: s_services_fleet
Desarrollo: 3
Punto: 2

ADD service fleet

---

s_criteria_expiration/__init__.py
s_criteria_expiration/__manifest__.py
s_criteria_expiration/data/criteria_expiration_menu.xml
s_criteria_expiration/i18n/es_MX.po
s_criteria_expiration/models/__init__.py
s_criteria_expiration/models/cargo_permit.py
s_criteria_expiration/models/insurance_policy.py
s_criteria_expiration/models/vehicle_service.py
s_criteria_expiration/security/ir.model.access.csv
s_criteria_expiration/views/cargo_permit_views.xml
s_criteria_expiration/views/insurance_policy_views.xml
s_criteria_expiration/views/vehicle_service_views.xml

MOD: s_criteria_expiration
Desarrollo: 3
Punto: 3

TEST: ADD criteria expiration

---

s_activity_car/__manifest__.py
s_activity_car/models/__init__.py
s_activity_car/models/inherit_vehicle_service.py
s_car_performance/models/inherit_fleet_vehicle_log_services.py
s_car_performance/models/inherit_fleet_vehicle_odometer.py
s_car_performance/views/inherit_fleet_vehicle_cost_view.xml
s_criteria_expiration/models/vehicle_service.py
s_custom_employee/models/inherit_hr_employee.py
s_custom_sale/views/inherit_sale_order_views.xml
s_insure_fleet/models/vehicle_activity.py
s_services_fleet/models/inherit_fleet_vehicle.py

Reverts networkerstech/sertresdelnorte#40

Revert "Sertres test 3"

---

s_car_performance/__manifest__.py
s_car_performance/i18n/es_MX.po
s_car_performance/models/__init__.py
s_car_performance/models/inherit_fleet_vehicle_log_services.py
s_car_performance/models/inherit_hr_expense.py

Crear odómetro desde el gasto cuando este se contabiliza Calcula el rendimiento del vehículo
Validar que el odómetro introducido sea mayor que el odómetro del vehículo Traducciones

TEST: IMP|s_car_performance|automatic_odometer_from_expense|DEV_ABT|16.0

---

s_expense_request/__manifest__.py
s_expense_request/i18n/es_MX.po
s_expense_request/models/hr_expense.py
s_expense_request/models/hr_expense_request.py
s_expense_request/views/hr_expense_request.xml
s_expense_request/views/inherit_hr_expense.xml

-Configurar la solicitud de gasto en el reporte de gastos -Calcular la comprobación del gasto teniendo en cuenta el importe del reporte

TEST: ADD-s_expense_request-state_for_expense_request

---

s_maintenance_tools_loan/__init__.py
s_maintenance_tools_loan/__manifest__.py
s_maintenance_tools_loan/data/ir_cron.xml
s_maintenance_tools_loan/i18n/es_MX.po
s_maintenance_tools_loan/models/__init__.py
s_maintenance_tools_loan/models/inherit_maintenance_equipment.py
s_maintenance_tools_loan/security/ir.model.access.csv
s_maintenance_tools_loan/views/inherit_maintenance_equipment_views.xml

Adicionar campos para la fecha de asignación y entrega Calcular estado del préstamo depediendo de estos
Tarea programada que actualiza el estado de los préstamos y notifica cuando se vencen

TEST: ADD-s_maintenance_tools_loan-loan_expiration-DEV_ABT-16.0

---

s_maintenance_tools_loan/__init__.py
s_maintenance_tools_loan/__manifest__.py
s_maintenance_tools_loan/data/ir_cron.xml
s_maintenance_tools_loan/i18n/es_MX.po
s_maintenance_tools_loan/models/__init__.py
s_maintenance_tools_loan/models/inherit_maintenance_equipment.py
s_maintenance_tools_loan/security/ir.model.access.csv
s_maintenance_tools_loan/views/inherit_maintenance_equipment_views.xml

Adicionar campos para la fecha de asignación y entrega Calcular estado del préstamo depediendo de estos
Tarea programada que actualiza el estado de los préstamos y notifica cuando se vencen

PROD: ADD-s_maintenance_tools_loan-loan_expiration-DEV_ABT-16.0

---

s_expense_request/__manifest__.py
s_expense_request/i18n/es_MX.po
s_expense_request/models/hr_expense.py
s_expense_request/models/hr_expense_request.py
s_expense_request/views/hr_expense_request.xml
s_expense_request/views/inherit_hr_expense.xml

-Configurar la solicitud de gasto en el reporte de gastos -Calcular la comprobación del gasto teniendo en cuenta el importe del reporte

PROD: ADD-s_expense_request-state_for_expense_request

---

s_car_performance/__manifest__.py
s_car_performance/i18n/es_MX.po
s_car_performance/models/__init__.py
s_car_performance/models/inherit_fleet_vehicle_log_services.py
s_car_performance/models/inherit_hr_expense.py

Crear odómetro desde el gasto cuando este se contabiliza Calcula el rendimiento del vehículo
Validar que el odómetro introducido sea mayor que el odómetro del vehículo Traducciones

PROD: IMP|s_car_performance|automatic_odometer_from_expense|DEV_ABT|16.0

---

s_insure_fleet/models/vehicle_activity.py

Se estaba buscando un partner con el mismo id del usuario para obtener el idioma

TEST: MOD de como se busca el odioma para mostrar las fechas en el fleet

---

s_custom_employee/__init__.py
s_custom_employee/__manifest__.py
s_custom_employee/data/s_custom_employee_data.xml
s_custom_employee/i18n/es_MX.po
s_custom_employee/models/inherit_hr_employee.py
s_custom_employee/security/ir.model.access.csv
s_custom_employee/views/inherit_hr_employee_views.xml
s_custom_employee/wizard/__init__.py
s_custom_employee/wizard/employee_resequence.py
s_custom_employee/wizard/employee_resequence.xml

Cambiar formato de secuencia para empleados
Asistente para resecuenciar empleados

TEST: empleados - el Registro debe iniciar por apellido paterno

---

s_insure_fleet/models/vehicle_activity.py

Se estaba buscando un partner con el mismo id del usuario para obtener el idioma

PROD: MOD de como se busca el odioma para mostrar las fechas en el fleet

---

s_analytic_stock/__manifest__.py
s_analytic_stock/i18n/es_MX.po
s_analytic_stock/models/inherit_analytic_account.py
s_analytic_stock/models/inherit_stock_move.py
s_analytic_stock/views/inherit_analytic_account_views.xml

Validar cuando se haga una devolución y esta tenga establecida la cuenta analítica que la cantidad devuelta no sea mayor que las cantidades enviadas

TEST: Inventario – Cuenta Analítica. FIX in video

---

s_services_fleet/models/inherit_fleet_vehicle.py

Se estaba pasando al create de fleet.vehicle.log.services un partner como vendor_id en lugar del id del partner

TEST: Servicios de los vehiculos

---

s_services_fleet/models/inherit_fleet_vehicle.py

Se estaba pasando al create de fleet.vehicle.log.services un partner como vendor_id en lugar del id del partner

PROD: Servicios de los Vehiculos

---

s_custom_employee/__init__.py
s_custom_employee/__manifest__.py
s_custom_employee/data/s_custom_employee_data.xml
s_custom_employee/i18n/es_MX.po
s_custom_employee/models/inherit_hr_employee.py
s_custom_employee/security/ir.model.access.csv
s_custom_employee/views/inherit_hr_employee_views.xml
s_custom_employee/wizard/__init__.py
s_custom_employee/wizard/employee_resequence.py
s_custom_employee/wizard/employee_resequence.xml

Cambiar formato de secuencia para empleados
Asistente para resecuenciar empleados

PROD: empleados - el Registro debe iniciar por apellido paterno

---

s_custom_employee/__init__.py
s_custom_employee/__manifest__.py
s_custom_employee/models/inherit_hr_employee.py
s_custom_employee/security/ir.model.access.csv
s_custom_employee/wizard/employee_resequence.py

Retornar al formato anterior de las secuencia de empleados

TEST: employee improve sequence

---

s_addenda_pepsico/data/pepsico.xml
s_addenda_pepsico/models/inherit_account_move.py
s_addenda_pepsico/views/inherit_account_move_views.xml

Mover campo s_addenda_pepsico de las líneas al formulario principal

TEST: Addenda Pepsico

---

s_custom_employee/models/inherit_hr_employee.py

Adicionar nuevos campos a public employee

TEST: Correccion del error en la secuencia de empleado

---

s_addenda_marelli/models/inherit_account_move.py
s_addenda_marelli/views/inherit_account_move.xml

Ocultar las columnas referentes a la addenda marelli en las líneas de la factura cuando esta no aplica

TEST: Addenda Marelli

---

s_custom_sale_rate/__manifest__.py
s_custom_sale_rate/models/inherit_account_move.py
s_custom_sale_rate/models/inherit_account_payment.py
s_custom_sale_rate/models/inherit_sale_order.py
s_custom_sale_rate/views/inherit_account_payment.xml

Tasa de cambio manual para facturas y pagos en adición a la de la orden de venta que ya existía

TEST: Tipo de Cambio

---

s_addenda_pepsico/data/pepsico.xml
s_addenda_pepsico/models/inherit_account_move.py
s_addenda_pepsico/views/inherit_account_move_views.xml

Mover campo s_addenda_pepsico de las líneas al formulario principal

PROD: Addenda Pepsico

---

s_addenda_marelli/models/inherit_account_move.py
s_addenda_marelli/views/inherit_account_move.xml

Ocultar las columnas referentes a la addenda marelli en las líneas de la factura cuando esta no aplica

PROD: Addenda Marelli

---

s_custom_employee/models/inherit_hr_employee.py

Adicionar nuevos campos a public employee

PROD: Correccion del Error de la secuencia de empleado
